config/routes.rb
DepViewer::Application.routes.draw do
  resources :projects
  resources :builds

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :project
  has_many :dependencies
  has_many :dependants, :class_name => 'Dependency', :foreign_key => 'dependency_build_id'
  attr_accessible :project_id, :build_number

  def project_name
  	return Project.find(self.project_id).name
  end
end

app/models/dependency.rb
class Dependency < ActiveRecord::Base
  belongs_to :build
  belongs_to :dependency_build, :class_name => 'Build'
  attr_accessible :build_id, :dependency_build_id

  def dependency_project_name(dependency_build_id)
  		return Project.find(Build.find(dependency_build_id).project_id).name
  end

  def dependency_build_number(dependency_build_id)
  		return Build.find(dependency_build_id).build_number
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :builds
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
	def show
		@build = Build.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def show
		@project = Project.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/builds/show.html.erb
<h1><%= @build.project_name + '-' + @build.build_number %></h1>
<h2>Dependencies</h2>
<ul>
	<% @build.dependencies.each do |dependency| %>
	<li><%= dependency.dependency_project_name(dependency.dependency_build_id) + '-' + dependency.dependency_build_number(dependency.dependency_build_id) %></li>
	<% end %>
</ul>
<h2>Dependants</h2>
<ul>
	<% @build.dependants.each do |dependant| %>
	<li><%= dependant.dependency_project_name(dependant.build_id) + '-' + dependant.dependency_build_number(dependant.build_id) %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepViewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Projects List</h1>
<ul>
<% @projects.each do |project| %>
<li><%= link_to project.name, project_path(project) %></li>
<% end %>
</ul>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<%= @project.description %>
<h2>Available Builds</h2>
<ul>
<% @project.builds.each do |build| %>
<li><%= link_to build.build_number, build_path(build) %></li>
<% end %>
</ul>